import { Button } from "@/components/ui/button";

const vulnerabilities = [
  {
    id: "VUL-042",
    name: "Authentication Bypass",
    target: "auth-service",
    severity: "CRITICAL",
    score: "9.8",
    status: "OPEN",
    discovered: "2 min ago",
  },
  {
    id: "VUL-039",
    name: "SQL Injection",
    target: "api-gateway",
    severity: "HIGH",
    score: "8.7",
    status: "OPEN",
    discovered: "8 min ago",
  },
  {
    id: "VUL-031",
    name: "Missing Security Headers",
    target: "web-client",
    severity: "MEDIUM",
    score: "6.4",
    status: "OPEN",
    discovered: "14 min ago",
  },
  {
    id: "VUL-027",
    name: "Weak Session Configuration",
    target: "auth-service",
    severity: "MEDIUM",
    score: "5.9",
    status: "ANALYZING",
    discovered: "21 min ago",
  },
  {
    id: "VUL-019",
    name: "Exposed Debug Endpoint",
    target: "payment-api",
    severity: "HIGH",
    score: "8.1",
    status: "PATCH READY",
    discovered: "31 min ago",
  },
];

function severityClass(severity: string) {
  if (severity === "CRITICAL") {
    return "border-red-400/20 bg-red-400/5 text-red-400";
  }

  if (severity === "HIGH") {
    return "border-orange-400/20 bg-orange-400/5 text-orange-400";
  }

  return "border-yellow-400/20 bg-yellow-400/5 text-yellow-400";
}

function statusClass(status: string) {
  if (status === "PATCH READY") {
    return "text-emerald-400";
  }

  if (status === "ANALYZING") {
    return "text-cyan-300";
  }

  return "text-white/40";
}

export default function Vulnerabilities() {
  return (
    <div>
      {/* Header */}
      <header className="glass-header flex min-h-20 items-center justify-between px-6 lg:px-8">
        <div>
          <p className="text-[10px] tracking-[0.25em] text-cyan-300/50">
            THREAT INTELLIGENCE
          </p>

          <h1 className="mt-1 text-xl font-semibold">
            Vulnerabilities
          </h1>
        </div>

        <Button className="bg-cyan-400 text-black hover:bg-cyan-300">
          Run Deep Scan
        </Button>
      </header>

      <div className="p-6 lg:p-8">

        {/* Summary */}
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {[
            ["Total Findings", "24"],
            ["Critical", "03"],
            ["High", "07"],
            ["Patch Ready", "05"],
          ].map(([label, value]) => (
            <div
              key={label}
              className="glass rounded-2xl p-5"
            >
              <p className="text-xs text-white/35">
                {label}
              </p>

              <p className="mt-4 text-3xl font-semibold">
                {value}
              </p>
            </div>
          ))}
        </div>

        {/* Filters */}
        <div className="glass mt-6 flex flex-col gap-3 rounded-2xl p-4 md:flex-row">
          <input
            placeholder="Search vulnerabilities..."
            className="h-10 flex-1 rounded-lg border border-white/10 bg-black/30 px-4 text-xs text-white outline-none placeholder:text-white/20 focus:border-cyan-400/30"
          />

          {["All", "Critical", "High", "Medium"].map((filter) => (
            <button
              key={filter}
              className={`rounded-lg border px-4 py-2 text-xs transition ${
                filter === "All"
                  ? "border-cyan-400/20 bg-cyan-400/10 text-cyan-300"
                  : "border-white/10 bg-white/5 text-white/40 hover:text-white"
              }`}
            >
              {filter}
            </button>
          ))}
        </div>

        {/* Vulnerability table */}
        <div className="glass mt-6 overflow-hidden rounded-2xl">

          <div className="border-b border-white/10 p-5">
            <h2 className="font-medium">
              Detected Vulnerabilities
            </h2>

            <p className="mt-1 text-xs text-white/30">
              Findings generated by autonomous security agents
            </p>
          </div>

          <div className="overflow-x-auto">

            <table className="w-full min-w-[850px]">
              <thead>
                <tr className="border-b border-white/10 text-left text-[9px] tracking-widest text-white/20">
                  <th className="px-5 py-4">VULNERABILITY</th>
                  <th className="px-5 py-4">TARGET</th>
                  <th className="px-5 py-4">SEVERITY</th>
                  <th className="px-5 py-4">CVSS</th>
                  <th className="px-5 py-4">STATUS</th>
                  <th className="px-5 py-4">DISCOVERED</th>
                  <th className="px-5 py-4"></th>
                </tr>
              </thead>

              <tbody>
                {vulnerabilities.map((vulnerability) => (
                  <tr
                    key={vulnerability.id}
                    className="border-b border-white/5 transition hover:bg-white/[0.025]"
                  >
                    <td className="px-5 py-5">
                      <div className="flex items-center gap-3">
                        <span
                          className={`h-2 w-2 rounded-full ${
                            vulnerability.severity === "CRITICAL"
                              ? "bg-red-400 shadow-[0_0_10px_rgba(248,113,113,0.7)]"
                              : vulnerability.severity === "HIGH"
                              ? "bg-orange-400"
                              : "bg-yellow-400"
                          }`}
                        />

                        <div>
                          <p className="text-xs font-medium">
                            {vulnerability.name}
                          </p>

                          <p className="mt-1 text-[9px] text-white/20">
                            {vulnerability.id}
                          </p>
                        </div>
                      </div>
                    </td>

                    <td className="px-5 py-5 text-xs text-white/45">
                      {vulnerability.target}
                    </td>

                    <td className="px-5 py-5">
                      <span
                        className={`rounded-full border px-3 py-1 text-[8px] tracking-widest ${severityClass(
                          vulnerability.severity
                        )}`}
                      >
                        {vulnerability.severity}
                      </span>
                    </td>

                    <td className="px-5 py-5 text-xs">
                      {vulnerability.score}
                    </td>

                    <td
                      className={`px-5 py-5 text-[9px] tracking-widest ${statusClass(
                        vulnerability.status
                      )}`}
                    >
                      {vulnerability.status}
                    </td>

                    <td className="px-5 py-5 text-xs text-white/30">
                      {vulnerability.discovered}
                    </td>

                    <td className="px-5 py-5">
                      <button className="text-xs text-cyan-300/60 hover:text-cyan-300">
                        Investigate →
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

          </div>
        </div>

        {/* AI Analysis */}
        <div className="glass-cyan mt-6 rounded-2xl p-6">

          <div className="flex items-start gap-4">

            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-cyan-400/20 bg-cyan-400/10 text-cyan-300">
              AI
            </div>

            <div>
              <p className="text-xs tracking-widest text-cyan-300/70">
                AI SECURITY ANALYSIS
              </p>

              <h3 className="mt-2 font-medium">
                3 vulnerabilities require immediate attention.
              </h3>

              <p className="mt-2 max-w-3xl text-sm leading-relaxed text-white/35">
                The autonomous analysis engine has identified an
                authentication bypass as the highest-risk finding.
                A potential remediation path is available in the
                Patch Center.
              </p>

              <Button
                variant="outline"
                className="mt-5 border-cyan-400/20 bg-cyan-400/5 text-cyan-300 hover:bg-cyan-400/10"
              >
                Open Patch Center →
              </Button>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
}